# Generated by Django 5.0.2 on 2024-04-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
            ],
        ),
    ]
