# Generated by Django 5.0.2 on 2024-05-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='id',
            new_name='bookid',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='age',
            new_name='bookname',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='gender',
            new_name='customername',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='project',
            name='password',
        ),
    ]
