# Generated by Django 5.0.2 on 2024-05-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_id_project_bookid_rename_age_project_bookname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Library',
        ),
    ]
